### ISSUE TITLE
wrong result

### ISSUE THREAD

**Issue by DanielRuf** [bradleyfalzon/sha1affected#1]
http://sha1affected.com/results?server=isotopeecommerce.org

`The certificates for isotopeecommerce.org do not contain SHA1 signatures and won't be affected.`
Sure?
`End Identity   *.isotopeecommerce.org, isotopeecommerce.org    2016-06-26  SHA1`

**Comment by bradleyfalzon** [comment]
Something isn't right there. I'll get a look at it over the next 24hrs. But you're right, it's a bug and thanks for the report.

**Comment by bradleyfalzon** [comment]
This has been resolved.

It was quite a bad mistake, I hadn't come across a SHA1 certificate with a SHA2 intermediate, so the code overwrote the fact it was SHA1 when looping through the certificates. I don't love this code.

Thanks again.

**Comment by DanielRuf** [comment]
You are welcome. Thanks for fixing this so fast.
